server:
  port: ${port:8001}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver    #
    url: jdbc:mysql://192.168.0.122:3306/agro?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=true
    username: root
    password: root@1020
    type: com.alibaba.druid.pool.DruidDataSource #type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
  redis:
    host: 192.168.0.122
    port: 6379
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  application:
    name: agro-admin

mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:

  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/





